services:
  - type: web
    name: bbscoin-tg-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: NOWPAYMENTS_API_KEY
        sync: false
      - key: GOOGLE_CREDENTIALS_B64
        sync: false
